name: azure-mcp-experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clonar Repo do Azure MCP Server
        run: git clone https://github.com/Azure/azure-mcp.git azure-mcp

      - name: Exibir conteudo dos diretorios
        run: |
          echo
          pwd
          echo
          ls -l
          echo
          echo
          cd azure-mcp
          pwd
          echo

      - name: Exibir conteudo do Dockerfile que sera empregado no build da imagem
        run: |
          cd azure-mcp
          cat Dockerfile
          ls -l
